### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by oztrix** [SwimOrDieSoftware/WordpressContestCodePlugin#1]
On activation:

Fatal error: Can’t use method return value in write context in /home/******/public_html/wp-content/plugins/contest-code-checker/admin/class-contest-code-checker-admin.php on line 487

Many Thanks,

**Comment by medelibero** [comment]
What version of the plug-in are you using and what version of PHP?

**Comment by medelibero** [comment]
I just released version 1.1.2 which fixes this issue for me.
