### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by ryanpst** [SwimOrDieSoftware/WordpressContestCodePlugin#2]
your plugin looks perfect for what I'm looking for but when I go to activate I get the following error:

Parse error: syntax error, unexpected end of file in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/contest-code-checker/admin/class-contest-code-checker-admin.php on line 579

(you'll see I'm running the bitnami AWS version of wordpress)

Anything you can do to help me get this going would be very much appreciated

**Comment by medelibero** [comment]
What version of PHP are you using?

**Comment by ryanpst** [comment]
Thanks for getting back to me.. I'm using PHP version 7.0.12

**Comment by medelibero** [comment]
Alright, I will try the plugin on that PHP version and hopefully I can reproduce the issue.

**Comment by ryanpst** [comment]
Hi Mike,

Just thought I'd check in to see if you've been able to replicate the error? 

Cheers

Ryan

**Comment by medelibero** [comment]
Sorry for the delay, I was traveling. I just released a fix (version 1.1.4) which should fix the problem you ran into.

**Comment by ryanpst** [comment]
You're a champion! I'll take a look. How can I donate by the way?

**Comment by medelibero** [comment]
If it is useful plugin for you, feel free to send me a donation via PayPal, email address mikede@mde-dev.com.
